version: 2

project_name: ex-ample

before:
  hooks:
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0

  targets:
  - linux_amd64
  - windows_amd64
  - android_arm64

  ldflags:
  - -s -w

archives:
- name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  formats:
  - zip
  format_overrides:
  - goos: linux
    formats:
    - tar.xz
  wrap_in_directory: true
  files:
  - LICENSE.md
  - README.md

announce:
  skip: true
