version: 2

project_name: ex-ample

before:
  hooks:
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0

  targets:
  - linux_amd64
  - windows_amd64
  - android_arm64

  ldflags:
  - -s -w
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -X main.builtBy=goreleaser
  - -X main.Version={{.Version}}
  - -X main.Revision={{.ShortCommit}}

archives:
- name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  formats:
  - tar.xz
  format_overrides:
  - goos: windows
    formats:
    - zip
  wrap_in_directory: true
  files:
  - LICENSE.md
  - README.md

announce:
  skip: true
